### ISSUE TITLE
How would i configure the connection to an external postgres instance

### ISSUE THREAD

**Issue by whysthatso** [theodo/falco#109]
#### Documentation Feedback

I'd like to run falco via the proposed docker-compose.yml, but i would rather use my existing postgresql instance on a different machine. in other django apps i'm running i would usually adjust the DATABASES block like so:

```
DATABASES = {
  'default': {
    'HOST': 'postgres.domain.net',
    'PORT': 5432,
    'ENGINE': 'django.db.backends.postgresql',
    'NAME': 'falco',
    'USER': 'falco',
    'PASSWORD': '{{ falco_db_pass }}',
    'TEST': {'CHARSET': 'UTF8'}
  }
}
```
This does not seem to have an effect.  I do not know the app well enough to understand where DATABASE_URL is being used, and how to possibly adjust it.

Can anybody point me in the right direction?

**Comment by whysthatso** [comment]
ok, nvmnd that was an easy one:

DATABASE_URL=postgres://db_user:db_pass@postgres_domain_or_ip:port/db_name

maybe this can make it into the docs a slight bit more explicitly?

**Comment by phacks** [comment]
Hi! Thank you for opening an issue, and helpfully including the solution 😄 

I think this definitely belong in the docs; would you consider updating it to include your solution? You can open a Pull Request directly from GitHub by following this link: https://github.com/theodo/falco/edit/master/docs/docs/getting-started/installation.mdx
