### ISSUE TITLE
configuring of project, add step to populate data

### ISSUE THREAD

**Issue by CoolCold** [theodo/falco#114]
#### Documentation Feedback
to populate list of possible audits, I needed to do manual run for task
![image](https://user-images.githubusercontent.com/316482/71860664-5dc60c00-3126-11ea-81da-67c34763d7c8.png)

this may be useful to reflect in documentation, otherwise unable to create project with empty audit section field.

**Comment by phacks** [comment]
@CoolCold Hi! Thank you for opening an issue, I agree that this can be a serious impediment on a first install.

Would you consider updating the docs to include this extra (but mandatory) step? You can open a Pull Request directly from GitHub by following this link: https://github.com/theodo/falco/edit/master/docs/docs/getting-started/configuring-your-first-project.md

**Comment by CoolCold** [comment]
here is it https://github.com/theodo/falco/pull/116

**Comment by phacks** [comment]
Out of curiosity, which way did you install Falco—Heroku or manual installation? Because I just tested a new Heroku install and the list of audit parameters was already populated.

**Comment by CoolCold** [comment]
@phacks I did it with manual installation.

**Comment by phacks** [comment]
Merged with #129!
