### ISSUE TITLE
Wrong translation in English

### ISSUE THREAD

**Issue by MParvin** [theodo/falco#120]

**Comment by MParvin** [comment]
I think in line `Visually complete (First view)` is different from `Visually complete (Repeat view)`, But in en.json line 189 is like line 193.

`    "WPTMetricFirstViewVisuallyComplete": {
      "name": "Visually Complete (First View)",
      "description": "Triggered when 100% of the pixels on the page reached their final position (for the first visit on website)"
    },
    "WPTMetricRepeatViewVisuallyComplete": {
      "name": "Visually Complete (Repeat View)",
      "description": "Triggered when 100% of the pixels on the page reached their final position (for the first visit on website)"
    },`

**Comment by phacks** [comment]
Thanks @MParvin for pointing that out, and @fargito for creating a PR! 😍
