### ISSUE TITLE
List of user's project lost on page refresh

### ISSUE THREAD

**Issue by clementdessoude** [theodo/falco#138]
#### Reproduction

Steps to reproduce:
1. Create two projects
2. Select "Mes Projets": you see your two projects
3. Select the first one
4. Refresh the page
5. Select "Mes Projets": you can only see your current project
 
#### Expected Behavior

You should be able to see the list of all your current projects.

#### Actual Behavior

You can only see your current project if you refresh the page. The call to the '/projects' route is not done if you refresh the page

#### Environment

- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOs

**Comment by phacks** [comment]
Thanks for reporting! 

That’s indeed a bug. Would you like (and have the time) to try and fix it? I can show you around the codebase if you need.

**Comment by clementdessoude** [comment]
Yes, I'll try to have a look ;)

**Comment by clementdessoude** [comment]
It's weird, it seems that the deploy with Heroku button didn't deploy the latest version of Falco, or am I missing something ?

=> I don't have the "Gérer les paramètres du projet" link here
<img width="444" alt="Screen Shot 2020-03-31 at 23 23 21" src="https://user-images.githubusercontent.com/25530077/78076422-aba98380-73a6-11ea-8e16-cd551de8546b.png">

And when I launch it locally, I got this:
<img width="389" alt="Screen Shot 2020-03-31 at 23 23 36" src="https://user-images.githubusercontent.com/25530077/78076412-a815fc80-73a6-11ea-8f63-12e132e70bd7.png">

**Comment by fargito** [comment]
Hello @clementdessoude I'm closing this since it seems the problem has been fixed. Feel free to reopen it if you notice it again :wink:
