### ISSUE TITLE
No automatic deploy on private instance

### ISSUE THREAD

**Issue by MathildeDuboille** [theodo/falco#163]
At this time, there is no update mechanism on falco private instance. For an already created instance, there is no way to update and get the latest features.

**Comment by phacks** [comment]
The Hasura documentation on how to update an instance deployed via a Heroku is clear and well written, maybe we should use it as a reference: https://hasura.io/docs/1.0/graphql/manual/deployment/heroku/updating.html

**Comment by fargito** [comment]
Thanks @phacks, I will close this now
