### ISSUE TITLE
Fresh docker install http://localhost:80  redirects to https://localhost and  gives ERR_CONNECTION_RESET 

### ISSUE THREAD

**Issue by bikker** [theodo/falco#221]
#### Reproduction

Steps to reproduce:
1.  install via docker
2.  open localhost:80
 
 
#### Expected Behavior

What behavior were you expecting to see?
: site opens

#### Actual Behavior

What behavior did you actually see?
http://localhost:80  redirects to https://localhost and  gives ERR_CONNECTION_RESET

Curl gives
HTTP/1.1 301 Moved Permanently
Server:
Date: Sat, 15 Aug 2020 19:38:11 GMT
Connection: close
Transfer-Encoding: chunked
Content-Type: text/html; charset=utf-8
Location: https://localhost/
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block

And log :
172.21.0.1 - - [15/Aug/2020:19:38:11 +0000] "GET / HTTP/1.1" 301 0 "-" "curl/7.64.0"
#### Environment
Docker install 
- Browser(s): Chrome ,ff ,edge
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu

**Comment by fargito** [comment]
Hello @bikker, are you trying to install the development version ?

**Comment by bikker** [comment]
yes i was trying as we need it running 24x7 so we can't keep ssh windows open ! seems like docker is not working properly

**Comment by bikker** [comment]
yes tried dev and prod version as per instructions but having same issues

**Comment by fargito** [comment]
Could you try http://localhost:3000 ? When using the development version, this is the port you should use. Port 80 is only used on the production server but requires a specific configuration

**Comment by bikker** [comment]
nothing on :3000 ! for dev version what are the correct docker-compose.yml  and .env.prod files?

**Comment by bikker** [comment]
Managed to get dev env but now i get the following error


Request Method: | GET
-- | --
http://localhost:8000/
3.0.7
TemplateDoesNotExist
index.html
/usr/local/lib/python3.7/site-packages/django/template/loader.py in select_template, line 47
/usr/local/bin/python
3.7.9
['/code',  '/code',  '/code',  '/usr/local/lib/python37.zip',  '/usr/local/lib/python3.7',  '/usr/local/lib/python3.7/lib-dynload',  '/usr/local/lib/python3.7/site-packages']
Mon, 14 Sep 2020 18:50:05 +0200
