### ISSUE TITLE
Falco private instance

### ISSUE THREAD

**Issue by moreiramarti** [theodo/falco#230]
Hello,

I'm wondering if it's possible to install falco on private instance (not using heroku) ?

Regards,
Martinho MOREIRA

**Comment by phacks** [comment]
Hi @moreiramarti! The steps to install falco manually are described in [this section](https://getfal.co/docs/getting-started/installation#deploying-with-docker-compose) of the docs.

This method is less tested though, you might find quirks or inconsistencies in the process. You can raise an issue here if you do :)

**Comment by moreiramarti** [comment]
Thanks, I will try that

**Comment by uhlhosting** [comment]
@moreiramarti any luck with deployment outside heroku?

**Comment by moreiramarti** [comment]
Hi 
Yes it works.
I asked me some digging but it's fine now

**Comment by uhlhosting** [comment]
Do you have some recommandations or best practices based on your experience @moreiramarti

**Comment by moreiramarti** [comment]
I've maid an ansible role
Feel free to take a look https://github.com/moreiramarti/falco_ansible_role
It's certainly not perfect but it helps

**Comment by uhlhosting** [comment]
@moreiramarti did I got this correct, falco will run remote tests against WebPageTest?

**Comment by phacks** [comment]
@uhlhosting that is correct yes. Falco only takes care of configuring and orchestrating the tests, and aggregating and displaying the results. The actual tests are run by WebPageTest.

**Comment by uhlhosting** [comment]
Anyhow I did not managed to make it yet run via docker, will dig more, into this. I did managed to deploy the private version hosted webpagetest.
