### ISSUE TITLE
Can't login into a fresh install with the default credentials

### ISSUE THREAD

**Issue by rgllm** [theodo/falco#235]
#### Reproduction

Steps to reproduce:
1. Fresh install to Heroku
2. Try to login with the default credentials `admin` : `admin`
 
#### Expected Behavior
Login into the application to change the default user.

#### Actual Behavior
Got prompt with this message: `Those credentials seem incorrect. Please try again.`

#### Environment

- Browser(s): Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by fargito** [comment]
Hello @rgllm, I cannot reproduce this bug, can you try with the latest version ? I have release version 1.2.0

**Comment by rgllm** [comment]
@fargito just installed version `1.2.0` and I can confirm that the issue no longer happens. Thanks 👍
