### ISSUE TITLE
Unable to change project when not admin on the displayed project

### ISSUE THREAD

**Issue by LeoAnesi** [theodo/falco#236]
#### Reproduction

Steps to reproduce:
1. Create a project A where you are admin
2. Create a project B where you are not admin
3. When you go on project A page you should be able to switch  to project B with the top bar menu
4. Check that on project B page you can't change the project
 
 
#### Expected Behavior

What behavior were you expecting to see?

I whould be able to change to my other projects even if I'm not admin of the current displayed one

#### Actual Behavior

What behavior did you actually see?

I'm enable to change to my other projects when I'm not admin of the displayed one

#### Environment

- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu

**Comment by fargito** [comment]
@LeoAnesi I couldn't reproduce. Is the bug that you only see one projet in the list of your projects ?

**Comment by fargito** [comment]
Ok i believe this should be fixed now
