### ISSUE TITLE
Deployment is a bit long

### ISSUE THREAD

**Issue by phacks** [theodo/falco#26]
As of now, the Heroku deployments are a bit long (~10 minutes).

This can be a bit annoying as Heroku Review Apps are used to preview PRs, meaning that one can only preview and test their changes after waiting for ~10 minutes.

@kraynel as you already slimmed down the Docker build, you might want to have a look at what can be optimized even more :)

**Comment by kraynel** [comment]
I used https://stackoverflow.com/a/52192327 to time the execution of each step of the docker build. Total build duration: 396s (local, no cache), i.e. 6 min 40 sec.

Here are the timings:
<img width="839" alt="image" src="https://user-images.githubusercontent.com/4620699/67498925-8b033200-f680-11e9-9564-5f8a6e7b67ba.png">

Slow steps:
- Fetch front dependencies (yarn install) -> 166s 
- Build front -> 103s
- Install back dependencies (pip) -> 105s

Possibilities to reduce these steps:
- Add cache to avoid fetching the front & back dependencies for every build (impossible with heroku build?)
- Fetch fewer librairies (front dev dependencies are required to build the prod)
- Improve front build time

**Comment by phacks** [comment]
Closed for now by #60, thanks @kraynel!
