### ISSUE TITLE
Deploying on Heroku team

### ISSUE THREAD

**Issue by enstyled** [theodo/falco#71]
When trying to deploy the application within a Heroku team it errors, because the teams cannot use free dynos and there is no way to specify otherwise.

**Comment by phacks** [comment]
Hi @enstyled! Indeed, the current “Deploy to Heroku” button does not work for teams.

I’ve created a branch off of `master` with a small change the `app.json` only: the dynos now are in the `hobby` pricing.

I’ve successfully tried and deployed the app from a Heroku team with this new version. Could you try and have a go at this button?

[![Deploy to Heroku](https://www.herokucdn.com/deploy/button.svg)](https://heroku.com/deploy?template=https://github.com/theodo/falco/tree/heroku-teams-button)

**Comment by phacks** [comment]
If that worked, we’ll have to look into keeping this branch in sync with the latest versions. I think this can be achieved with GitHub Actions.

**Comment by enstyled** [comment]
Thank you for the fast reaction, @phacks! I just tried the button above and it works.

I know you can pass some variables through the button in order to make different configurations, but I am not sure if setting the dyno formation this way is supported.
