### ISSUE TITLE
feat(docs): add issue templates for issues and pull requests

### ISSUE THREAD

**Issue by donroyco** [theodo/falco#72]
Currently there are a lot of ways people adding issues and pull requests to this repository. It's great that they contribute to this repo, but I think it's better when that can be streamlined and every issue and/or PR provides the same information.

There's this [GitHub Help article](https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates) about issue and pull request templates which can help in setting this up.

I think a great example of issue templates are the ones from [Angular Components](https://github.com/angular/components/tree/master/.github/ISSUE_TEMPLATE) and [Moment](https://github.com/moment/moment/tree/develop/.github/ISSUE_TEMPLATE).

**Comment by phacks** [comment]
Hi! I really like the idea, and I just learned that you could have different templates for different needs.

From the examples you suggested, I like the brevity of Angular Components. I’m thinking that we can start small, and add new additions to the templates as the need arises.

Would you like to submit a Pull Request for this?

**Comment by donroyco** [comment]
@phacks Seems like a good idea to start small. Let me set up a PR soonish.

**Comment by phacks** [comment]
Closed by #75
