### ISSUE TITLE
All strings are untranslated

### ISSUE THREAD

**Issue by sjelfull** [theodo/falco#76]
I'm psyched about testing Falco!

However, after when deploying to Heroku, I'm just getting untranslated strings (`Welcome.no_project` etc.) through the app.

I _think_ I saw an error related to `t` in the console, but I can't get it to show again.

Any ideas?

I didn't do anything other than use the Deploy to Heroku button.

**Comment by phacks** [comment]
Hi @sjelfull! Indeed, Falco is translated in French and English, but it looks like if your browser is in another language, no default (english) translation will be displayed.

I’ll try and push a fix today!

**Comment by phacks** [comment]
In the meantime, you _could_ set your browser in English to see proper translations if you’d like to test Falco 🙂

**Comment by sjelfull** [comment]
Aha, I had a hunch that was the case. Do you know if that is a config thing in `react-intl` or something? I tried searching the docs for 2 secs and couldn't find anything, or else I would have tried to submit a PR.

Found this btw: https://github.com/formatjs/react-intl/issues/1089#issuecomment-361743913

Will switch to English for testing tho.

**Comment by phacks** [comment]
Did a bit of testing locally, and it looks like we can manually default to English in the [`Root.tsx`](https://github.com/theodo/falco/blob/master/frontend/src/components/Root/Root.tsx) component (responsible for i18n):

```tsx
  const userLanguage =
    (navigator.languages && navigator.languages[0]) || navigator.language || 'fr';
  // Split locales with a region code
  let userLanguageWithoutRegionCode = userLanguage.toLowerCase().split(/[_-]+/)[0];
  let localizedMessages = locales[userLanguage] || locales[userLanguageWithoutRegionCode];
  
  // Default to english if user’s locale is not available
  if (!localizedMessages) {
    userLanguageWithoutRegionCode = "en";
    localizedMessages = locales["en"];
  }

  return (
    <IntlProvider locale={userLanguageWithoutRegionCode} messages={localizedMessages}>
      ...
    </IntlProvider>
  )
```

That solution seems a little bit easier than the one you suggested, although I’m not sure that it’d catch all edge cases.

**Comment by sjelfull** [comment]
It looks like a good improvement to me. Yeah, i'll try to submit a PR 🥇

**Comment by phacks** [comment]
@sjelfull Hi! Did you get the chance to have a look at the bug? Please let me know if I can help you in any way 😄

**Comment by phacks** [comment]
@sjelfull Hi again! I don’t want to sound pushy, but have you had time to investigate the issue? No biggie if you didn’t! And if you’d rather leave the PR for someone else it’s totally fine too. Anyway, I’m always available if you need some help

**Comment by sjelfull** [comment]
Thanks for fixing this! I got caught by the holiday preparations and travelling for work, so had 0 time.

**Comment by phacks** [comment]
No worries @sjelfull! And happy holidays 🎅
