### ISSUE TITLE
Automate new releases with GitHub Actions

### ISSUE THREAD

**Issue by phacks** [theodo/falco#81]
#### Feature Description

When a new git tag is created, we need to do the following to create a new release:

- Update the CHANGELOG.md
- Update the version the Heroku Button points to
- Rebase the `heroku-teams-button` branch to the new release
- Create a new GitHub release

Some of those actions _could_ be automated with GitHub Actions, which would make it easier and less error-prone to push new releases

#### Use Case

This would be useful to the repository maintainers.

**Comment by kraynel** [comment]
Not possible using Github Actions as long as Theodo is on the old Github billing plan.

**Comment by phacks** [comment]
True that! Thanks for the heads up, I’m closing the issue for now :)
