### ISSUE TITLE
Time To Interactive is different from WebPageTest audit

### ISSUE THREAD

**Issue by jeanphilippeds** [theodo/falco#87]
#### Reproduction

Steps to reproduce:
1. Check TTI given by Falco
2. Open an audit
3. Check TTI given by WPT
 
 
#### Expected Behavior

What behavior were you expecting to see?
The values are equal

#### Actual Behavior

What behavior did you actually see?

#### Environment

TTI (Falco): 6,02s
[TTI (WPT): 2078ms](https://www.webpagetest.org/video/compare.php?tests=191107_6N_5006fad11caa69a29343c70e60ea8ce8-r%3A1-c%3A0&thumbSize=200&ival=500&end=full)

**Comment by phacks** [comment]
Hi @jeanphilippeds! the relevant piece of code is there:

https://github.com/theodo/falco/blob/c4713d0ab38f3a8a4601b1594fd22a4be170933d/backend/audits/wpt_utils/normalizer.py#L50-L55

WebPageTests has many metrics related to interactivity (some of them sometimes absent), the way we are handling it in Falco seems to not reflect 100% the way it’s displayed in WebPageTest.org. Maybe some searching around in WPT’s codebase can show us what metric they actually use/discard?
