### ISSUE TITLE
Root package.json is possibly useless

### ISSUE THREAD

**Issue by phacks** [theodo/falco#97]
Following #94, it looks like I introduced the root `package.json` file as a “fix” to some GitHub security notification in #20. However, two things strike me as strange:

- Instead of bumping the versions in `frontend/package.json`, I created a whole new one, which doesn’t really make sense;
- I bumped the `lodash` version even though `lodash` is not listed in the project’s frontend dependencies. Moreover, `@types/lodash` is listed as DevDependencies although `lodash` isn’t.

I guess I was pretty tired when I made those changes, but they were harmless so I consider myself lucky.

A suggested course of action:

- Bump `react-app-rewire-webpack-bundle-analyzer` in `frontend/package.json` to `1.1.0` (to fix the initial security issue) and run the `yarn analyze` command in `frontend` to see if it’s still working correctly;
- Remove the `@types/lodash` dev dependency and run `yarn start` to see if no TS errors appear.

This would have the following benefits:

- Fix the security issue in `react-app-rewire-webpack-bundle-analyzer`
- Clean up the repository
- Ease up the setup of the Falco project locally as, for now, people may be tempted to run `yarn && yarn start` in the root dir instead of `frontend/`

This PR is up for grabs if anyone’s interested (maybe @toqueteos?)!

**Comment by toqueteos** [comment]
Sure, I can send a PR in a couple hours when I get home! 🎉

**Comment by toqueteos** [comment]
`yarn analyze` keeps complaining about certain imports which do actually have a proper import path written down so I cannot get this to compile. Is master green?

**Comment by phacks** [comment]
Huh, I’ll try and check later on. Haven’t launch analyze in quite some time, so master might not be green indeed.

**Comment by phacks** [comment]
`master` is green, at least on my machine—just tried `yarn && yarn analyze` and got the following report:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/2587348/70981666-de5c9400-20b5-11ea-91d7-40b6fcb0058a.png">

However, this warning I got may be something to investigate: `Setting NODE_PATH to resolve modules absolutely has been deprecated in favor of setting baseUrl in jsconfig.json (or tsconfig.json if you are using TypeScript) and will be removed in a future major release of create-react-app.`

**Comment by toqueteos** [comment]
I'll try again with a clean repo, just in case I've messed up something.

**Comment by phacks** [comment]
Just in case, here are my `yarn` and `node` versions: 

```
➜  yarn -v
1.17.3
➜  node -v
v10.15.3
```

**Comment by toqueteos** [comment]
Ok, got it to work, finally!

The two proposed changes work but I found that there's two uses of lodash (`frontend/src/services/i18n/intl.ts` and `frontend/src/redux/auditResults/sagas.ts`) but no `lodash` in `frontend/package.json`.

@phacks can you check if you have it installed? And if so, which version?

**Comment by phacks** [comment]
Oooh, good catch! Here’s my output of `yarn why lodash`:

```
➜  frontend git:(master) yarn why lodash
yarn why v1.17.3
[1/4] 🤔  Why do we have the module "lodash"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "lodash@4.17.11"
```

Hope that helps!

**Comment by toqueteos** [comment]
I cannot get this to build after adding `lodash@4.17.11` to the proper `package.json` (`frontend/package.json`) and upgrading `react-app-rewire-webpack-bundle-analyzer` from  `1.0.1` to `1.1.0`. I'm unassigning me from this so someone else can try it.

**Comment by phacks** [comment]
@toqueteos Sorry to hear that, thanks for giving it a go! I’ll try on my end to fix this and hope that I’ll be luckier.
